// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileService exposes filesystem operations to the frontend panels.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Conflicts returns the names of sources that already exist in destDir.
 */
export function Conflicts(sources: string[] | null, destDir: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(2001743014, sources, destDir);
}

/**
 * Copy recursively copies each source into destDir. Existing items are
 * replaced (folders are merged) only when overwrite is set. Progress is
 * reported under the given job id; cancelling the call stops the copy and
 * removes partially copied items.
 */
export function Copy(job: string, sources: string[] | null, destDir: string, overwrite: boolean): $CancellablePromise<void> {
    return $Call.ByID(505847122, job, sources, destDir, overwrite);
}

/**
 * DeletePermanently removes the given paths without using the Trash.
 */
export function DeletePermanently(paths: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(1304132677, paths);
}

export function Home(): $CancellablePromise<string> {
    return $Call.ByID(2045991304);
}

/**
 * List returns the entries of a directory. Paths starting with "~" are
 * expanded to the user's home directory.
 */
export function List(path: string): $CancellablePromise<$models.Listing | null> {
    return $Call.ByID(3183709331, path);
}

export function MakeDir(parent: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(4161545064, parent, name);
}

/**
 * Move moves each source into destDir, copying across devices.
 */
export function Move(job: string, sources: string[] | null, destDir: string, overwrite: boolean): $CancellablePromise<void> {
    return $Call.ByID(3811242802, job, sources, destDir, overwrite);
}

/**
 * Open launches the file with the system's default application.
 */
export function Open(path: string): $CancellablePromise<void> {
    return $Call.ByID(3932797943, path);
}

/**
 * ReadText returns up to maxViewBytes of a file for the built-in viewer.
 */
export function ReadText(path: string): $CancellablePromise<$models.FileText | null> {
    return $Call.ByID(4223971624, path);
}

export function Rename(path: string, newName: string): $CancellablePromise<string> {
    return $Call.ByID(1462832321, path, newName);
}

/**
 * Trash moves the given paths to the system Trash. Items that cannot be
 * trashed are reported back so the user can decide to delete them for good.
 */
export function Trash(paths: string[] | null): $CancellablePromise<$models.TrashResult | null> {
    return $Call.ByID(1486438983, paths);
}

/**
 * Watch replaces the set of watched folders with the ones open in any tab.
 */
export function Watch(dirs: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(213795786, dirs);
}
