// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Entry {
    "name": string;
    "path": string;
    "isDir": boolean;
    "isLink": boolean;
    "hidden": boolean;
    "size": number;

    /**
     * unix milliseconds
     */
    "modTime": number;
    "mode": string;
    "ext": string;
}

export interface FileText {
    "path": string;
    "content": string;
    "truncated": boolean;
    "binary": boolean;
    "size": number;
}

export interface Listing {
    "path": string;

    /**
     * empty at filesystem root
     */
    "parent": string;
    "entries": Entry[] | null;
}

/**
 * Progress is emitted as the progressEvent while a copy or move runs.
 */
export interface Progress {
    "job": string;

    /**
     * "scan", "copy" or "done"
     */
    "phase": string;
    "done": number;
    "total": number;
    "files": number;
    "totalFiles": number;
    "current": string;
}

export interface TrashResult {
    /**
     * paths that could not be moved to the Trash
     */
    "failed": string[] | null;

    /**
     * first failure reason
     */
    "message": string;
}
